// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/Sayfargo/yax-url-shortener/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockURLShortener creates a new instance of MockURLShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLShortener {
	mock := &MockURLShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLShortener is an autogenerated mock type for the URLShortener type
type MockURLShortener struct {
	mock.Mock
}

type MockURLShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLShortener) EXPECT() *MockURLShortener_Expecter {
	return &MockURLShortener_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function for the type MockURLShortener
func (_mock *MockURLShortener) CreateShortURL(ctx context.Context, url string, uid string) (string, error) {
	ret := _mock.Called(ctx, url, uid)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, url, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, url, uid)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, url, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortener_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockURLShortener_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - uid string
func (_e *MockURLShortener_Expecter) CreateShortURL(ctx any, url any, uid any) *MockURLShortener_CreateShortURL_Call {
	return &MockURLShortener_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", ctx, url, uid)}
}

func (_c *MockURLShortener_CreateShortURL_Call) Run(run func(ctx context.Context, url string, uid string)) *MockURLShortener_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLShortener_CreateShortURL_Call) Return(s string, err error) *MockURLShortener_CreateShortURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLShortener_CreateShortURL_Call) RunAndReturn(run func(ctx context.Context, url string, uid string) (string, error)) *MockURLShortener_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateURLBatch provides a mock function for the type MockURLShortener
func (_mock *MockURLShortener) CreateURLBatch(ctx context.Context, req []service.CreateURLBatchRequest, uid string) ([]service.CreateURLBatchResponse, error) {
	ret := _mock.Called(ctx, req, uid)

	if len(ret) == 0 {
		panic("no return value specified for CreateURLBatch")
	}

	var r0 []service.CreateURLBatchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []service.CreateURLBatchRequest, string) ([]service.CreateURLBatchResponse, error)); ok {
		return returnFunc(ctx, req, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []service.CreateURLBatchRequest, string) []service.CreateURLBatchResponse); ok {
		r0 = returnFunc(ctx, req, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.CreateURLBatchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []service.CreateURLBatchRequest, string) error); ok {
		r1 = returnFunc(ctx, req, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortener_CreateURLBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateURLBatch'
type MockURLShortener_CreateURLBatch_Call struct {
	*mock.Call
}

// CreateURLBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req []service.CreateURLBatchRequest
//   - uid string
func (_e *MockURLShortener_Expecter) CreateURLBatch(ctx any, req any, uid any) *MockURLShortener_CreateURLBatch_Call {
	return &MockURLShortener_CreateURLBatch_Call{Call: _e.mock.On("CreateURLBatch", ctx, req, uid)}
}

func (_c *MockURLShortener_CreateURLBatch_Call) Run(run func(ctx context.Context, req []service.CreateURLBatchRequest, uid string)) *MockURLShortener_CreateURLBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []service.CreateURLBatchRequest
		if args[1] != nil {
			arg1 = args[1].([]service.CreateURLBatchRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockURLShortener_CreateURLBatch_Call) Return(createURLBatchResponses []service.CreateURLBatchResponse, err error) *MockURLShortener_CreateURLBatch_Call {
	_c.Call.Return(createURLBatchResponses, err)
	return _c
}

func (_c *MockURLShortener_CreateURLBatch_Call) RunAndReturn(run func(ctx context.Context, req []service.CreateURLBatchRequest, uid string) ([]service.CreateURLBatchResponse, error)) *MockURLShortener_CreateURLBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function for the type MockURLShortener
func (_mock *MockURLShortener) GetOriginalURL(ctx context.Context, shortCode string) (string, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortener_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockURLShortener_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLShortener_Expecter) GetOriginalURL(ctx any, shortCode any) *MockURLShortener_GetOriginalURL_Call {
	return &MockURLShortener_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, shortCode)}
}

func (_c *MockURLShortener_GetOriginalURL_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLShortener_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLShortener_GetOriginalURL_Call) Return(s string, err error) *MockURLShortener_GetOriginalURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLShortener_GetOriginalURL_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (string, error)) *MockURLShortener_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function for the type MockURLShortener
func (_mock *MockURLShortener) GetUserURLs(ctx context.Context, uid string) ([]service.GetURLsResponse, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []service.GetURLsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]service.GetURLsResponse, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []service.GetURLsResponse); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.GetURLsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLShortener_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockURLShortener_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockURLShortener_Expecter) GetUserURLs(ctx any, uid any) *MockURLShortener_GetUserURLs_Call {
	return &MockURLShortener_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, uid)}
}

func (_c *MockURLShortener_GetUserURLs_Call) Run(run func(ctx context.Context, uid string)) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLShortener_GetUserURLs_Call) Return(getURLsResponses []service.GetURLsResponse, err error) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Return(getURLsResponses, err)
	return _c
}

func (_c *MockURLShortener_GetUserURLs_Call) RunAndReturn(run func(ctx context.Context, uid string) ([]service.GetURLsResponse, error)) *MockURLShortener_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}
