// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUrlShortener creates a new instance of MockUrlShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlShortener {
	mock := &MockUrlShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUrlShortener is an autogenerated mock type for the UrlShortener type
type MockUrlShortener struct {
	mock.Mock
}

type MockUrlShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlShortener) EXPECT() *MockUrlShortener_Expecter {
	return &MockUrlShortener_Expecter{mock: &_m.Mock}
}

// CreateShortUrl provides a mock function for the type MockUrlShortener
func (_mock *MockUrlShortener) CreateShortUrl(ctx context.Context, url string) (string, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlShortener_CreateShortUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortUrl'
type MockUrlShortener_CreateShortUrl_Call struct {
	*mock.Call
}

// CreateShortUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockUrlShortener_Expecter) CreateShortUrl(ctx any, url any) *MockUrlShortener_CreateShortUrl_Call {
	return &MockUrlShortener_CreateShortUrl_Call{Call: _e.mock.On("CreateShortUrl", ctx, url)}
}

func (_c *MockUrlShortener_CreateShortUrl_Call) Run(run func(ctx context.Context, url string)) *MockUrlShortener_CreateShortUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlShortener_CreateShortUrl_Call) Return(s string, err error) *MockUrlShortener_CreateShortUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUrlShortener_CreateShortUrl_Call) RunAndReturn(run func(ctx context.Context, url string) (string, error)) *MockUrlShortener_CreateShortUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalUrl provides a mock function for the type MockUrlShortener
func (_mock *MockUrlShortener) GetOriginalUrl(ctx context.Context, shortCode string) (string, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalUrl")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlShortener_GetOriginalUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalUrl'
type MockUrlShortener_GetOriginalUrl_Call struct {
	*mock.Call
}

// GetOriginalUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockUrlShortener_Expecter) GetOriginalUrl(ctx any, shortCode any) *MockUrlShortener_GetOriginalUrl_Call {
	return &MockUrlShortener_GetOriginalUrl_Call{Call: _e.mock.On("GetOriginalUrl", ctx, shortCode)}
}

func (_c *MockUrlShortener_GetOriginalUrl_Call) Run(run func(ctx context.Context, shortCode string)) *MockUrlShortener_GetOriginalUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlShortener_GetOriginalUrl_Call) Return(s string, err error) *MockUrlShortener_GetOriginalUrl_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUrlShortener_GetOriginalUrl_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (string, error)) *MockUrlShortener_GetOriginalUrl_Call {
	_c.Call.Return(run)
	return _c
}
