// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerator creates a new instance of MockGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerator {
	mock := &MockGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

type MockGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerator) EXPECT() *MockGenerator_Expecter {
	return &MockGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockGenerator
func (_mock *MockGenerator) Generate(alphabet string, size int) (string, error) {
	ret := _mock.Called(alphabet, size)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (string, error)); ok {
		return returnFunc(alphabet, size)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) string); ok {
		r0 = returnFunc(alphabet, size)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(alphabet, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - alphabet string
//   - size int
func (_e *MockGenerator_Expecter) Generate(alphabet any, size any) *MockGenerator_Generate_Call {
	return &MockGenerator_Generate_Call{Call: _e.mock.On("Generate", alphabet, size)}
}

func (_c *MockGenerator_Generate_Call) Run(run func(alphabet string, size int)) *MockGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerator_Generate_Call) Return(s string, err error) *MockGenerator_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGenerator_Generate_Call) RunAndReturn(run func(alphabet string, size int) (string, error)) *MockGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
