// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/Sayfargo/yax-url-shortener/internal/model"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) Create(ctx context.Context, shortenedUrl model.ShortenedUrl) error {
	ret := _mock.Called(ctx, shortenedUrl)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortenedUrl) error); ok {
		r0 = returnFunc(ctx, shortenedUrl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockURLRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenedUrl model.ShortenedUrl
func (_e *MockURLRepository_Expecter) Create(ctx any, shortenedUrl any) *MockURLRepository_Create_Call {
	return &MockURLRepository_Create_Call{Call: _e.mock.On("Create", ctx, shortenedUrl)}
}

func (_c *MockURLRepository_Create_Call) Run(run func(ctx context.Context, shortenedUrl model.ShortenedUrl)) *MockURLRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShortenedUrl
		if args[1] != nil {
			arg1 = args[1].(model.ShortenedUrl)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_Create_Call) Return(err error) *MockURLRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLRepository_Create_Call) RunAndReturn(run func(ctx context.Context, shortenedUrl model.ShortenedUrl) error) *MockURLRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) CreateBatch(ctx context.Context, shortenedUrls []model.ShortenedUrl) error {
	ret := _mock.Called(ctx, shortenedUrls)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.ShortenedUrl) error); ok {
		r0 = returnFunc(ctx, shortenedUrls)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockURLRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockURLRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenedUrls []model.ShortenedUrl
func (_e *MockURLRepository_Expecter) CreateBatch(ctx any, shortenedUrls any) *MockURLRepository_CreateBatch_Call {
	return &MockURLRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, shortenedUrls)}
}

func (_c *MockURLRepository_CreateBatch_Call) Run(run func(ctx context.Context, shortenedUrls []model.ShortenedUrl)) *MockURLRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.ShortenedUrl
		if args[1] != nil {
			arg1 = args[1].([]model.ShortenedUrl)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_CreateBatch_Call) Return(err error) *MockURLRepository_CreateBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockURLRepository_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, shortenedUrls []model.ShortenedUrl) error) *MockURLRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) Get(ctx context.Context, shortCode string) (string, error) {
	ret := _mock.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, shortCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockURLRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLRepository_Expecter) Get(ctx any, shortCode any) *MockURLRepository_Get_Call {
	return &MockURLRepository_Get_Call{Call: _e.mock.On("Get", ctx, shortCode)}
}

func (_c *MockURLRepository_Get_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_Get_Call) Return(s string, err error) *MockURLRepository_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockURLRepository_Get_Call) RunAndReturn(run func(ctx context.Context, shortCode string) (string, error)) *MockURLRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLs provides a mock function for the type MockURLRepository
func (_mock *MockURLRepository) GetURLs(ctx context.Context, uid uuid.UUID) ([]model.ShortenedUrl, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetURLs")
	}

	var r0 []model.ShortenedUrl
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ShortenedUrl, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ShortenedUrl); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShortenedUrl)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockURLRepository_GetURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLs'
type MockURLRepository_GetURLs_Call struct {
	*mock.Call
}

// GetURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockURLRepository_Expecter) GetURLs(ctx any, uid any) *MockURLRepository_GetURLs_Call {
	return &MockURLRepository_GetURLs_Call{Call: _e.mock.On("GetURLs", ctx, uid)}
}

func (_c *MockURLRepository_GetURLs_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockURLRepository_GetURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockURLRepository_GetURLs_Call) Return(shortenedUrls []model.ShortenedUrl, err error) *MockURLRepository_GetURLs_Call {
	_c.Call.Return(shortenedUrls, err)
	return _c
}

func (_c *MockURLRepository_GetURLs_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) ([]model.ShortenedUrl, error)) *MockURLRepository_GetURLs_Call {
	_c.Call.Return(run)
	return _c
}
